#!/bin/bash
# Script de correction automatique pour CI/CD et développement local
# Ce script corrige automatiquement les erreurs de linting et peut créer un commit

set -e

echo "========================================"
echo "MCParr - CI Auto-Fix & Commit"
echo "========================================"

cd "$(dirname "$0")/.."

AUTO_COMMIT="${AUTO_COMMIT:-false}"
BRANCH_NAME="${CI_COMMIT_BRANCH:-$(git rev-parse --abbrev-ref HEAD)}"
CHANGES_MADE=false

# ============================================================================
# Backend Fixes
# ============================================================================
if [ -d "src/backend" ]; then
    echo ""
    echo "🐍 Backend - Correction automatique..."
    cd src/backend

    if command -v poetry &> /dev/null; then
        # Sauvegarde l'état avant les corrections
        git diff --name-only > /tmp/before_backend.txt 2>/dev/null || true

        # Corrections automatiques
        echo "  → Ruff auto-fix (safe + unsafe)..."
        poetry run ruff check src/ --fix --unsafe-fixes || true

        echo "  → Black formatage..."
        poetry run black src/ || true

        # Génération des rapports
        echo "  → Génération des rapports..."
        mkdir -p reports
        poetry run ruff check src/ --output-format=json > reports/ruff-report.json 2>&1 || true
        poetry run ruff check src/ --output-format=text > reports/ruff-report.txt 2>&1 || true

        # Compte les erreurs restantes
        REMAINING_ERRORS=$(poetry run ruff check src/ 2>&1 | grep -c "Found.*errors" || echo "0")

        echo "  ℹ️  Erreurs restantes: $REMAINING_ERRORS"

        # Vérifie s'il y a eu des changements
        git diff --name-only > /tmp/after_backend.txt 2>/dev/null || true
        if ! diff /tmp/before_backend.txt /tmp/after_backend.txt > /dev/null 2>&1; then
            CHANGES_MADE=true
            echo "  ✅ Corrections appliquées au backend"
        else
            echo "  ℹ️  Aucun changement au backend"
        fi
    else
        echo "  ⚠️  Poetry non trouvé"
    fi

    cd ../..
fi

# ============================================================================
# Frontend Fixes
# ============================================================================
if [ -d "src/frontend" ]; then
    echo ""
    echo "🎨 Frontend - Correction automatique..."
    cd src/frontend

    if command -v npm &> /dev/null; then
        # Sauvegarde l'état avant les corrections
        git diff --name-only > /tmp/before_frontend.txt 2>/dev/null || true

        # Corrections automatiques
        echo "  → ESLint auto-fix..."
        npm run lint -- --fix 2>/dev/null || echo "  ℹ️  Erreurs résiduelles"

        # Génération des rapports
        echo "  → Génération des rapports..."
        mkdir -p reports
        npm run lint -- --format json --output-file reports/eslint-report.json 2>/dev/null || true
        npm run lint -- --format stylish > reports/eslint-report.txt 2>/dev/null || true

        # Vérifie s'il y a eu des changements
        git diff --name-only > /tmp/after_frontend.txt 2>/dev/null || true
        if ! diff /tmp/before_frontend.txt /tmp/after_frontend.txt > /dev/null 2>&1; then
            CHANGES_MADE=true
            echo "  ✅ Corrections appliquées au frontend"
        else
            echo "  ℹ️  Aucun changement au frontend"
        fi
    else
        echo "  ⚠️  npm non trouvé"
    fi

    cd ../..
fi

# ============================================================================
# Auto-commit (si activé)
# ============================================================================
if [ "$AUTO_COMMIT" = "true" ] && [ "$CHANGES_MADE" = "true" ]; then
    echo ""
    echo "📝 Création d'un commit avec les corrections..."

    git config user.name "${GIT_USER_NAME:-GitLab CI}"
    git config user.email "${GIT_USER_EMAIL:-ci@gitlab.com}"

    git add -A

    COMMIT_MSG="chore: auto-fix linting errors

- Applied ruff --fix and black formatting (backend)
- Applied eslint --fix (frontend)

🤖 Auto-generated by CI pipeline
Branch: ${BRANCH_NAME}
Pipeline: ${CI_PIPELINE_URL:-local}"

    git commit -m "$COMMIT_MSG" || echo "⚠️ Rien à commiter"

    # Push si dans le CI
    if [ -n "$CI" ] && [ -n "$CI_REPOSITORY_URL" ]; then
        echo "  → Push vers ${BRANCH_NAME}..."
        git push "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "HEAD:${BRANCH_NAME}"
        echo "  ✅ Changements poussés vers GitLab"
    else
        echo "  ℹ️  Mode local - les changements ne sont pas poussés"
        echo "  ℹ️  Exécutez 'git push' pour envoyer les corrections"
    fi
else
    echo ""
    if [ "$CHANGES_MADE" = "false" ]; then
        echo "✅ Aucune correction nécessaire"
    else
        echo "ℹ️  Corrections appliquées localement"
        echo "ℹ️  Utilisez AUTO_COMMIT=true pour commiter automatiquement"
    fi
fi

echo ""
echo "========================================"
echo "✅ Auto-fix terminé!"
echo "========================================"

# Affiche le statut git
if command -v git &> /dev/null; then
    echo ""
    git status --short
fi
